GesPerson/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = "GesPerson"
urlpatterns = [
    path('', views.index, name='index'),
    path("add_teacher", views.add_teacher, name='add_teacher'),
    path("teachers/show_t", views.show_t, name='show_t'),
    path('teachers/edit/<int:id>', views.edit, name='edit'),

    path("add_student", views.add_student, name='add_student'),
    path("students/show_s", views.show_s, name='show_s'),
    path('students/edit_s/<int:id>', views.edit_s, name='edit_s'),


]

GestionPersonnel/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GesPerson.urls')),
]

GesPerson/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.
class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth_date = models.DateField()
    tel = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)

    class Meta:
        abstract = True

class Teacher(Person):
    speciality = models.CharField(max_length=50)
    def __str__(self):
        speciality = str(self.speciality)
        return self.first_name + " " + self.last_name +" "+ self.birth_date + " " + self.tel + " " + self.email + " " + self.speciality



class Student(Person):
    pathway = models.CharField(max_length=50)
    def __str__(self):
        pathway = str(self.pathway)
        return self.first_name + " " + self.last_name +" "+ self.birth_date + " " + self.tel + " " + self.email + " " + self.pathway

GesPerson/forms.py
from django import forms
from django.forms import ModelForm
from GesPerson.models import Teacher, Student


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'birth_date', 'tel', 'email', 'speciality']

        # labels = {"first_name" : "Votre nom "}
    def first_name(self):
        first_name = self.cleaned_data['first_name']

        if any(char.isdigit() for char in first_name):
            raise forms.ValidationError("Le chiffre n'est pas permis")
        return first_name

    def last_name(self):
        last_name = self.cleaned_data['last_name']

        if any(char.isdigit() for char in last_name):
            raise forms.ValidationError("Le chiffre n'est pas permis")
        return last_name
        

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'birth_date', 'tel', 'email', 'pathway']

    def first_name(self):
        first_name = self.cleaned_data['first_name']

        if any(char.isdigit() for char in first_name):
            raise forms.ValidationError("Le chiffre n'est pas permis")
        return first_name

    def last_name(self):
        last_name = self.cleaned_data['last_name']

        if any(char.isdigit() for char in last_name):
            raise forms.ValidationError("Le chiffre n'est pas permis")
        return last_name

GesPerson/views.py
from django.shortcuts import render
from GesPerson.forms import TeacherForm, StudentForm
from django.shortcuts import render,  redirect
from django.db.models import Count


from GesPerson.models import Teacher, Student

def index(request):
   return render(request, "accueil/index.html")
# Create your views here.
def add_teacher(request):
    if request.method == "POST":
        form = TeacherForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("teachers/show_t")
            except:
                pass
    else:
        form = TeacherForm()
       
        return render(request, "teachers/add_teacher.html", {'form':form})
    
def show_t(request):
    recupteacher = Teacher.objects.all()
    nobreteacher = recupteacher.count()
    return render(request, 'teachers/show_t.html', {'recupteacher': recupteacher, 'nobreteacher' : nobreteacher})
    


def edit(request, id):
    teachers = Teacher.objects.get(id=id)
    return render(request, 'teachers/edit.html', {'teachers': teachers})


def update_teachers(request, id):
    teachers = teachers.objects.get(id=id)
    form = TeacherForm(request.POST, instance=teachers)
    if form.is_valid():
        form.save()
        return redirect('teachers/show_t')
    return render(request, 'teachers/update_teachers.html', {'teachers':teachers})



    
#---------------------------------etudiant-----------------------------------------


def add_student(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("students/show_s")
            except:
                pass
    else:
        form = StudentForm()
       
        return render(request, "students/add_student.html", {'form':form})
    
def show_s(request):
    recupstudent = Student.objects.all()
    nobreetudiant = recupstudent.count()
    return render(request, 'students/show_s.html', {'recupstudent': recupstudent, 'nobreetudiant' : nobreetudiant})


def edit_s(request, id):
    students = Student.objects.get(id=id)
    return render(request, 'students/edit_s.html', {'students': students})


def update_students(request, id):
    students = Student.objects.get(id=id)
    form = StudentForm(request.POST, instance=students)
    if form.is_valid():
        form.save()
        return redirect('students/show_t')
    return render(request, 'students/update_students.html', {'students':students})

GesPerson/templates/accueil/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {margin: 0;}
        ul.topnav {
          list-style-type: none;
          margin: 0;
          padding: 0;
          overflow: hidden;
          background-color: #333;
        }
        
        ul.topnav li {float: left;}
        
        ul.topnav li a {
          display: block;
          color: white;
          text-align: center;
          padding: 14px 16px;
          text-decoration: none;
        }
        
        ul.topnav li a:hover:not(.active) {background-color: #111;}
        
        ul.topnav li a.active {background-color: #04AA6D;}
        
        ul.topnav li.right {float: right;}
        
        @media screen and (max-width: 600px) {
          ul.topnav li.right, 
          ul.topnav li {float: none;}
        }
        
        
        #customers {
          font-family: Arial, Helvetica, sans-serif;
          border-collapse: collapse;
          width: 100%;
        }
        
        #customers td, #customers th {
          border: 1px solid #ddd;
          padding: 8px;
        }
        
        #customers tr:nth-child(even){background-color: #f2f2f2;}
        
        #customers tr:hover {background-color: #ddd;}
        
        #customers th {
          padding-top: 12px;
          padding-bottom: 12px;
          text-align: left;
          background-color: #04AA6D;
          color: white;
        }
        
        .dimi{
            display: flex;
            justify-content : space-between;
            align-items : center;
            padding: 10px 5%;
        }
        .dimi a{
            background : darkblue;
            padding: 10px;
            cursor: pointer;
            text-decoration : none;
            border-radius: 15px;
            color : white;
            
        }
        .di{
        padding: 0 5%;
        }

        form{
          margin: auto;
          padding: 10px;
          display: grid;
          background-color: rgb(243, 227, 227);
          width: 15rem;
        }
        form input{
          padding: 3px;
          margin-bottom: 8px;
        }
    </style>
    <title>Document</title>
</head>
<body>
	<ul class="topnav">
	  <li><a class="active" href="#home">GESTION PERSONNELS</a></li>
	  <li><a href="{% url 'GesPerson:add_teacher' %}">TeacherForm</a></li>
    <li><a href="{% url 'GesPerson:add_student' %}">StudentForm</a></li>
    <li><a href="{% url 'GesPerson:show_t' %}">Listes Teacher</a></li>
    <li><a href="{% url 'GesPerson:show_s' %}">Listes Student</a></li>
    
	 
	</ul>
    {% block content %}{% endblock %}
	
</body>
</html>

GesPerson/templates/students/add_student.html
{% extends "accueil/index.html" %}
{% block content %}
    <h1 style="text-align: center;">Enroll Student</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.first_name.label_tag }} 
        {{ form.first_name }} 

        {{ form.last_name.label_tag }}
        {{ form.last_name }} 
        {{ form.birth_date.label_tag }}
        {{ form.birth_date }} 
        {{ form.tel.label_tag }}
        {{ form.tel }} 
        {{ form.email.label_tag }}
        {{ form.email }} 

        {{ form.pathway.label_tag }}
        {{ form.pathway }} 

        <button type="submit">Enregistrer</button>
    </form>

{% endblock %}

GesPerson/templates/students/edit_s.html
{% extends "accueil/index.html" %}
{% block content %}
    <h1>Update students</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div>
            <p>Nom</p>
            <div>
                <input type="text" name="first_name" value="{{students.first_name}}">
            </div>
        </div>
        <div>
            <p>Prenom</p>
            <div>
                <input type="text" name="last_name" value="{{students.last_name}}">
            </div>
        </div>
        <div>
            <p>Student Name</p>
            <div>
                <input type="text" name="first_name" value="{{students.first_name}}">
            </div>
        </div>
        <div>
            <p>Date naissance</p>
            <div>
                <input type="text" name="birth_date" value="{{students.birth_date}}">
            </div>
        </div>
        <div>
            <p>Student Contact</p>
            <div>
                <input type="text" name="tel" value="{{students.tel}}">
            </div>
        </div>

        <div>
            <p>Student Contact</p>
            <div>
                <input type="text" name="email" value="{{students.email}}">
            </div>
        </div>

        <div>
            <p>Student Contact</p>
            <div>
                <input type="text" name="pathway" value="{{students.pathway}}">
            </div>
        </div>
        <div>
            <br>
            <button type="submit">update</button>
        </div>
    </form>

{% endblock %}

GesPerson/templates/students/show_s.html
{% extends "accueil/index.html" %}
{% block content %}
    <div class="di">
		<div class="dimi">
			<h1>LISTES DES STUDENTS</h1>
      <small><h4>Nombre de teachers</h4><h1>{{ nobreetudiant }}</h1></small>
			<a href="{% url 'GesPerson:add_teacher' %}">Ajouter utilisateur</a>
		</div>
	
		<table id="customers">
		  <tr>
		    <th>Nom</th>
            <th>Prenom</th>
            <th>datenaissance</th>
            <th>telephone</th>
            <th>email</th>
            <th>pathway</th>
		    <th>Update</th>
        </tr>
        {% for teach in recupstudent %}
        <tr>
            <td>{{ teach.first_name }}</td>
            <td>{{ teach.last_name }}</td>
            <td>{{ teach.birth_date }}</td>
            <td>{{ teach.tel }}</td>
            <td>{{ teach.email }}</td>
            <td>{{ teach.pathway }}</td>
            <td>
                <a href="edit_s/{{teach.id}}">Update</a>
            </td>
        </tr>
        {% endfor %}
		</table>
	</div>

{% endblock %}

GesPerson/templates/teachers/add_teacher.html
{% extends "accueil/index.html" %}
{% block content %}
    <h1 style="text-align: center;">Enroll teachers</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.first_name.label_tag }} 
        {{ form.first_name }} 

        {{ form.last_name.label_tag }}
        {{ form.last_name }} 
        {{ form.birth_date.label_tag }}
        {{ form.birth_date }} 
        {{ form.tel.label_tag }}
        {{ form.tel }} 
        {{ form.email.label_tag }}
        {{ form.email }} 
        
        {{ form.speciality.label_tag }}
        {{ form.speciality }} 

        <button type="submit">Enregistrer</button>
    </form>

{% endblock %}

speciality

GesPerson/templates/teachers/edit.html
{% extends "accueil/index.html" %}
{% block content %}
    <h1>Enroll teachers</h1>
    <form action="" method="post">
        {% csrf_token %}
        <div>
            <br>
            <p>Update details</p>
        </div>

        <div>
            <p>Nom</p>
            <div>
                <input type="text" name="first_name" value="{{teachers.first_name}}">
            </div>
        </div>
        <div>
            <p>Prenom</p>
            <div>
                <input type="text" name="last_name" value="{{teachers.last_name}}">
            </div>
        </div>
        <div>
            <p>Teacher Name</p>
            <div>
                <input type="text" name="first_name" value="{{teachers.first_name}}">
            </div>
        </div>
        <div>
            <p>Date naissance</p>
            <div>
                <input type="text" name="birth_date" value="{{teachers.birth_date}}">
            </div>
        </div>
        <div>
            <p>Teacher Contact</p>
            <div>
                <input type="text" name="tel" value="{{teachers.tel}}">
            </div>
        </div>

        <div>
            <p>Teacher Contact</p>
            <div>
                <input type="text" name="email" value="{{teachers.email}}">
            </div>
        </div>

        <div>
            <p>Teacher Contact</p>
            <div>
                <input type="text" name="speciality" value="{{teachers.speciality}}">
            </div>
        </div>
        <div>
            <br>
            <button type="submit">update</button>
        </div>
    </form>

{% endblock %}

GesPerson/templates/teachers/show_t.html
{% extends "accueil/index.html" %}
{% block content %}
    <div class="di">
		<div class="dimi">
			<h1>LISTES DES  TEACHERS</h1>
      <small><h4>Nombre de teachers</h4><h1>{{ nobreteacher }}</h1></small>
			<a href="{% url 'GesPerson:add_teacher' %}">Ajouter utilisateur</a>
		</div>
	
		<table id="customers">
		  <tr>
		    <th>Nom</th>
            <th>Prenom</th>
            <th>datenaissance</th>
            <th>telephone</th>
            <th>email</th>
            <th>speciality</th>
		    <th>Update</th>
        </tr>
        {% for teach in recupteacher %}
        <tr>
            <td>{{ teach.first_name }}</td>
            <td>{{ teach.last_name }}</td>
            <td>{{ teach.birth_date }}</td>
            <td>{{ teach.tel }}</td>
            <td>{{ teach.email }}</td>
            <td>{{ teach.speciality }}</td>
            <td>
                <a href="edit/{{teach.id}}">Update</a>
            </td>
        </tr>
        {% endfor %}
		</table>
	</div>

{% endblock %}